#这些配置会被保留，如果和下面的重复则会被覆盖
spring:
  profiles:
    active:
    - dev
---
server:
  port: 80
spring:
  profiles: dev
  application:
    name: feignclient-dept-config
eureka:
  instance:
    instance-id: feignClient-dev
    prefer-ip-address: true
  client:
    #register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
feign:
  hystrix:
    enabled: true
---
server:
  port: 80
spring:
  profiles: test
  application:
    name: feignclient-dept-config
eureka:
  instance:
    instance-id: feignClient-test
    prefer-ip-address: true
  client:
    #register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:6001/eureka/,http://eureka7002.com:6002/eureka/
feign:
  hystrix:
    enabled: true