spring:
  profiles:
    active:
    - dev
---
server:
  port: 7003
spring:
  profiles: dev
  application: microservicecloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7003.com    # eureka 服务端的实例名称
  client:
    register-with-eureka: false # false 表示不向注册中心注册
    fetch-registry: false       # false 表示自己就是注册中心，我的职责就是维护实例，并不需要去检索Eureka服务
    service-url:                # 设置eureka Client向eureka Server 注册服务的使用地址
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
--- 
server:
  port: 6003
spring:
  profiles: test
  application: microservicecloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7003.com    # eureka 服务端的实例名称
  client:
    register-with-eureka: false # false 表示不向注册中心注册
    fetch-registry: false       # false 表示自己就是注册中心，我的职责就是维护实例，并不需要去检索Eureka服务
    service-url:                # 设置eureka Client向eureka Server 注册服务的使用地址
      defaultZone: http://eureka7002.com:6002/eureka/,http://eureka7001.com:6001/eureka/