spring:
  profiles:
    active:
    - dev
--- 
server:
  port: 8001
spring:
  profiles: dev
  application: microservicecloud-config-dept-client
--- 
server:
  port: 9001
spring:
  profiles: test
  application: microservicecloud-config-dept-client