spring:
  profiles:
    active:
      - test
---
spring:
  profiles: dev
eureka:
  client:                   # 客户端注册进Eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: gateway-9527-7001.com # 自定义服务名称信息 - eureka服务列表右边名称
    prefer-ip-address: true                 # 访问路径可以显示ip  - 点击eureka服务列表名称，右下角或者点击进入会换成IP
---
spring:
  profiles: test
eureka:
  client:                   # 客户端注册进Eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:6001/eureka/,http://eureka7002.com:6002/eureka/
  instance:
    instance-id: gateway-9527-6001.com # 自定义服务名称信息 - eureka服务列表右边名称
    prefer-ip-address: true                 # 访问路径可以显示ip  - 点击eureka服务列表名称，右下角或者点击进入会换成IP
